### ISSUE TITLE
Setup Interface

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-repository#1]
As a higher-level abstraction `Repository` should provide a way of setting up a simpler persistence layer where relations and commands are automatically generated. You could setup repositories for specific adapters.

Interface idea:

``` ruby
class PostgresRepository < ROM::Repository::Base # still Base until we remove it from rom core
  gateway :default do |config|
    config.uri = 'postgres://localhost/rom'
  end
end

class UserRepository < PostgresRepository
  # a repo must be able to access 1 or more relations!
  relations :users

  # a repo can access many commands, we can apply defaults too
  commands users: [:create, :update, :delete]

  def active
    users.where(active: true)
  end

  def by_id(id)
    users.where(id: id)
  end
end

user_repo = UserRepository.new # just works

# works the same way as now
user_repo.active.by_id(1)

# CUD interface
user_repo.create(user)
user_repo.update(user)
user_repo.delete(user)
```

**Comment by endash** [comment]
More crucially, (yet) another layer of abstraction is needed to remove the (undocumented) tight coupling to rom-sql. There was just enough indirection in the code to make it difficult to track down why it was relying on an `attributes` method that didn't exist. Turns out, I was already trying to use rom-repo as if the higher level abstraction were the current behaviour: persistence method details in the relation, repository to compose relations from the passed `env` without caring about their persistence strategies. 

In this view, it's not so much a new, higher-level abstraction as it is re-aligning the implementation with the current-level abstraction, and inserting a mid-level abstraction to handle special casing around the mapper generation.

**Comment by solnic** [comment]
@endash I just started with support for rom-sql that would work OOTB with rom-repository. Repository relies on few plugins, we should move sql-specific plugins to rom-sql and extend other adapters with support for those plugins too. I guess we could consider moving some of those plugins to rom core so that rom-repository have them available for all adapters.

I don't think we need another **layer of abstraction**. I really want to keep this as simple as possible, so that rom-repository can leverage various features implemented as plugins and expose its higher level API.

I'm sorry you had trouble tracking down that exception. I should fix it ASAP and improve the documentation.

**Comment by solnic** [comment]
Oh one more thing - there's no special-casing around mapper generation. For relation composition the same setup is needed regardless of the adapter.

**Comment by endash** [comment]
@solnic OK, that's perfect, then. I didn't exhaustively audit the code so I was making an educated guess that the mapper generation (`attributes` -> mapper has attributes... let's call it a day for that investigation) had something to do with it.

**Comment by solnic** [comment]
@endash no, the only adapter-specific part is the logic behind auto-combine and auto-wrap, those plugins are sql-specific, it should be trivial to build same plugins for other adapters though. That's one of the (many) cool things about this architecture, it all boils down to defining relations.

**Comment by endash** [comment]
Armed with that knowledge, perusing the source makes a lot more sense. 

Regarding the interface mockup above: would the new behaviour be opt-in? I, personally, prefer the notion of a static repository class which is reliant on a configuration being passed on initialization, as it provides ultimate flexibility while keeping "magic" to a minimum. One class supporting two very different use-cases isn't ideal.

**Comment by solnic** [comment]
My idea is to be able to configure an abstract repository which has its own ROM env configured through the DSL (`gateway do .. end`) and every repo that inherits from it will have access to relations from configured gateways. This way we always have a constructor that receives an auto-injected env but you can always just pass in your own ROM env (it's possible there might be use-cases for that).

> One class supporting two very different use-cases isn't ideal.

WDYM?

**Comment by endash** [comment]
> > One class supporting two very different use-cases isn't ideal.
> 
> WDYM?

It sounds to me like there'd be a single class (currently Base) that would provide both the current behaviour (pass in `env` manually) and a new DSL-based behaviour that would, essentially, incorporate into an abbreviated form all the semantics around setting up that `env`. I'd propose that the base class should remain basic, and any auto-generated-via-dsl functionality be in a subclass (which then just passes the env up to super). Or alternatively, the DSL could be a separate client class entirely where, again, the generated env just gets passed in as it is now. (rom = Rom.generate { |r| r.gateway... }; repo = MyRepository.new rom). Third alternative is an opt-in mixin.

Now, I don't doubt that as implementations go the DSL handling will be properly encapsulated into its own internal class no matter what. My concerns are twofold with some overlap:

(1) In a general sense, I'm leery of transparently folding otherwise independent configuration into what should by rights merely be a client class. It provides a shortcut for the developer, but obscures that fact at the same time, documentation notwithstanding. I think the same ease-of-use could be provided while either maintaining the same interface or otherwise providing cues (such as an AutoRepository class or whatnot) that there is a lower level of abstraction for which the class is merely a convenience layer.

(2) Long-term, as a developer, I don't like having to subclass kitchen sink classes (when exactly you hit that point is a matter of opinion), and would much prefer that the stripped down base class remain separate from the user-friendly version, even if those code paths never get hit in my subclasses.

**Comment by endash** [comment]
And the use case for wanting to pass in `env` instead of using the inline DSL is to keep the user's repository classes completely separate from the implementation detail

**Comment by solnic** [comment]
@endash gotcha, thanks for the explanation

I'll try to come up with other API ideas, please share if you have some :)

**Comment by blaix** [comment]
> class which is reliant on a configuration being passed on initialization

Given what I've seen in rom and from @solnic, I was surprised to see repository not work this way.

I'm also still having trouble understanding when a method should be on a relation vs when it should be on a repository.

**Comment by solnic** [comment]
@blaix encapsulating data-access in relations make a lot of sense for complex apps although I'd say _most_ of the apps are complex enough to have query logic encapsulated in relations. It's really up to you to decide. ie you can do `users.join(:addresses, id: :user_id).where(name: "Foo").combine_children(many: tasks.where { priority > 1 })` but that's poor encapsulation and harder to test individual data-access logic in isolation, that's why I'd prefer `users.with_address.combine_children(many: tasks.important)`.

Having said that - repositories can be used as a flat data-access layer where relations are not separated, so all query logic lives in repositories. Personally I prefer to think of repositories as a data-access layer that's closer to the domain, so I want to use domain language there and compose relations into domain structures, rather than to deal with query interfaces of the adapters.

I hope this helps a bit. Let me know if I should clarify more.

**Comment by blaix** [comment]
> Personally I prefer to think of repositories as a data-access layer that's closer to the domain

So adding a repository layer lets you have a layer that's closer to the storage logic (relation) and a layer on top of that that's closer to the business logic (repository), instead of having 1) every possible type of data access on one class (relation) or 2) breaking encapsulation to compose queries outside of your data-access objects.

That makes sense now. Thanks!

Now I can also imagine some complex scenarios where you could have multiple repositories using the same relation(s) for multiple domains... neat.

**Comment by solnic** [comment]
> class which is reliant on a configuration being passed on initialization
> 
> > Given what I've seen in rom and from @solnic, I was surprised to see repository not work this way.

It felt like "meh" I have to admit :) That's why we're now discussing how to tackle it properly. I've got some ideas, will share them here soon.

**Comment by solnic** [comment]
Excluding the command part - do you have any ideas of the api for setting up repos?

**Comment by solnic** [comment]
This was a stupid idea so I'm closing this. `rom` setup will always be handled by the core APIs, it makes no sense to complicate the stack.
