### ISSUE TITLE
CRUD Repository idea

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-repository#13]
Maybe it would be a good idea to provide a simplified CRUD repository interface, assuming we have an adapter with support for schema, we could have something like this:

``` ruby
class Users < ROM::Relation[:sql]
  schema do
    attribute :id, Types::Int
    attribute :name, Types::String
    attribute :age, Types::Int
  end
end

# that's not yet supported in dry-data but super easy to add
UserModel = Dry::Data::Struct(Users.schema)

class UserRepo < ROM::Repository::CRUD # probably a stupid name
end

user_repo = UserRepo.new(rom)

user = user_repo.save(UserModel.new(name: "Jane", age: 21))
user_repo.update(user, name: "Jane Doe")
user_repo.detele(user)
```

Thoughts?

**Comment by savroff** [comment]
It can work for something simple, but I not sure, that would great for more complex project. But for hight level it's look nice. For new users it can simplify things, especially if users still have ActiveRecord in mind.

**Comment by solnic** [comment]
Yeah that is the reason for its existance actually. A simplified crud api
for simple use cases.

**Comment by robinetmiller** [comment]
Where is `User` defined (ie. `User.new`)?

**Comment by solnic** [comment]
My bad. Should be `UserModel.new`

**Comment by endash** [comment]
My high level view, with further thoughts to come on #14:

Overly simplified and built for beginners/AR refugees aren't real concerns, in my view. This is in response not only to @savroff's comment but also a general theme that has run through discussions on the topic, historically. The great benefit of ROM over ORMs is that this functionality is properly architected, encapsulated, and adequately isolated from the rest of the app. If this feature stops being useful—either as an app grows or as a developer begins to use it for more complex apps—then they simply excise it and replace it with something more suitable. Neglecting this use case because it isn't as robust as a solution that might be called for by other use cases entirely is like refusing to build a bridge over a river because it won't ever be as rock solid as the two motorways you need to connect. Beginners need this, simple apps/scripts need this, and ROM as a project needs this if it (and its development philosophy) is going to appeal to a greater number of ruby devs.

:+1:

**Comment by cflipse** [comment]
I like the proposed interface around the repository methods, _but_

I do think we need to make sure that there are some clean / reasonable extension points.  The job of a repository is to serve as an adapter between the relations and the domain models, and it would be good if there was a reasonable way to say "update the `user` re(cord|elation) with _these_ attributes from user, and the `user_roles` relation with the contents of this array.

Also, there should probably be something around that lets you specify a primary key, if (for example) you use a GUID rather than an `id` field.  That feels maybe more like it belongs with a given relation than a repository, but I'm not sure (since at least some part of the repository seems to be around _avoiding_ building `Relation` classes ...

I'm also not sure how I feel about that schema object embedded in the relation.  it might be bad practice, but I've had enough occasions where I've added SQL joins to a relation, and fixing a strict one-to-one mapping between a relation and the fields returned feels somewhat too constrained, at first blush.

**Comment by solnic** [comment]
@cflipse natural keys and custom keys will be supported, don't worry about this.

To support "updating a user" we need to create an interface for specifying read/write models, otherwise it makes no sense. So in example you could have a user with an address that you use to both read and write. Then you can have features like updating a user where the method signature is as simple as `Repo#update(user, new_attributes)` and we can calculate the changeset to see what actually "changed". One remark though - I will still promote immutable models, no need to change them, we only need them to calculate changesets.

Re schema, its intention is not to constrain you, it's meant to serve as the canonical source of information about _the base relation_. We can infer a lot of behavior from a schema, like command input handlers with low level db coercions, automatic methods for composing relations based on schema info etc. There is a lot of valuable information that we can encode within schemas, this will allow us to provide convenient interfaces to work with relations in a structured way while still being able to freely compose relations however we want for complex use cases.

Remember that you always have access to relations and it is recommended to construct relation views that are aligned with the structures that your applications need. Mapping to objects is done via repo + model backend (and I strongly recommend using dry-data for that).

**Comment by solnic** [comment]
This is now done via `Repository#command` API which is used by `commands` macro that automatically generates `CUD` methods for the root relation.
